# Generated by Django 5.2.7 on 2025-10-10 02:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
        ('patients', '0003_hospital_alter_department_name_department_hospital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('brand_name', models.CharField(blank=True, help_text='Lab chain name (e.g., Dr. Lal PathLabs, SRL)', max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField(blank=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('accreditation', models.CharField(blank=True, help_text='NABL, CAP, ISO certifications', max_length=200)),
                ('home_sample_collection', models.BooleanField(default=True)),
                ('online_reports', models.BooleanField(default=True)),
                ('emergency_services', models.BooleanField(default=False)),
                ('offers_blood_tests', models.BooleanField(default=True)),
                ('offers_urine_tests', models.BooleanField(default=True)),
                ('offers_imaging', models.BooleanField(default=False)),
                ('offers_cardiology', models.BooleanField(default=False)),
                ('offers_pathology', models.BooleanField(default=True)),
                ('offers_microbiology', models.BooleanField(default=True)),
                ('opens_at', models.TimeField(default='07:00')),
                ('closes_at', models.TimeField(default='21:00')),
                ('is_24_hours', models.BooleanField(default=False)),
                ('average_turnaround_hours', models.IntegerField(default=24, help_text='Average time for routine tests')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Standard discount %', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Admin verified lab')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=2, default=4.5, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Lab Facility',
                'verbose_name_plural': 'Lab Facilities',
                'ordering': ['-is_verified', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('blood', 'Blood Tests'), ('urine', 'Urine Tests'), ('imaging', 'Imaging (X-Ray, CT, MRI)'), ('cardio', 'Cardiac Tests'), ('culture', 'Culture Tests'), ('biopsy', 'Biopsy'), ('other', 'Other Tests')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preparation_required', models.TextField(blank=True, help_text='Special preparation needed (fasting, etc.)')),
                ('duration_minutes', models.IntegerField(help_text='Approximate duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabFacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='lab_facility_images/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='patients.labfacility')),
            ],
            options={
                'verbose_name': 'Lab Facility Image',
                'verbose_name_plural': 'Lab Facility Images',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabFacilityReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('service_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('accuracy_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('speed_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('cleanliness_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='patients.labfacility')),
            ],
            options={
                'verbose_name': 'Lab Facility Review',
                'verbose_name_plural': 'Lab Facility Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('scheduled', 'Scheduled'), ('sample_collected', 'Sample Collected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT (Immediate)')], default='routine', max_length=20)),
                ('ordered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('sample_collected_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('clinical_notes', models.TextField(blank=True, help_text='Clinical indication for test')),
                ('special_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.department')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.labtest')),
            ],
            options={
                'ordering': ['-ordered_date'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.TextField(help_text='Main result value or findings')),
                ('reference_range', models.CharField(blank=True, max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('critical', 'Critical'), ('pending', 'Pending Review')], default='pending', max_length=20)),
                ('interpretation', models.TextField(blank=True, help_text="Doctor's interpretation")),
                ('attachments', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='patients.laborder')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_results', to='doctors.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabFacilityTestPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('turnaround_hours', models.IntegerField(default=24, help_text='Result delivery time')),
                ('home_collection_available', models.BooleanField(default=True)),
                ('home_collection_charge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_prices', to='patients.labfacility')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_prices', to='patients.labtest')),
            ],
            options={
                'verbose_name': 'Lab Test Price',
                'verbose_name_plural': 'Lab Test Prices',
                'ordering': ['price'],
                'unique_together': {('lab_facility', 'test')},
            },
        ),
    ]
