# Generated by Django 4.2.25 on 2025-10-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_add_teleappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teleappointment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
